import {newCharacter,validateCharacter,confirmCharacterData} from '../creation-v2/creator-service.mjs';
import {attributes,categories,proficiencyGroups,financeTiers,rules} from '../creation-v2/catalog.mjs';
import {allocate,adjust,attributePointsRemaining} from '../creation-v2/allocation-engine.mjs';
import {categoryStatus,proficiencyRemaining} from '../creation-v2/point-source-ledger.mjs';
import {readRun,newRun,rollFinance,developerFinance} from '../creation-v2/finance.mjs';
const $=q=>document.querySelector(q),all=q=>[...document.querySelectorAll(q)],KEY='clearwater-life-creator-v4';
let s;try{s=JSON.parse(localStorage.getItem(KEY))||newCharacter();if(s.version!==4)s=newCharacter()}catch{s=newCharacter()}
let run=readRun()||newRun();let message='',detail='',mobileDetail=false;
const titles=['基本資料','家庭經濟','能力值','技能','熟練度','背景','最終確認'];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(s))}
function pageErrors(p){
 if(p===0){const e=[];if(!s.basic.name.trim())e.push('請輸入姓名');const m=+s.basic.month,d=+s.basic.day,days=[31,29,31,30,31,30,31,31,30,31,30,31];if(!m||!d||d>days[m-1])e.push('請選擇有效生日');if(!s.basic.gender)e.push('請選擇性別');return e}
 if(p===1)return run.locked?[]:['請先投擲並鎖定家庭經濟'];
 if(p===2)return attributePointsRemaining(s)===0?[]:['能力值尚未分配完 250 點'];
 if(p===3){const e=[];if(!s.motherTongue)e.push('請選擇母語');for(const id of Object.keys(categories)){const z=categoryStatus(s,id);if(z.remaining<0)e.push(id+' 超額 '+(-z.remaining)+' 點')}return e}
 if(p===4)return proficiencyRemaining(s)<0?['熟練度點數超額']:[];
 if(p===5)return [];
 return validateCharacter(s,run)
}
function canEnter(page){for(let i=0;i<page;i++)if(pageErrors(i).length)return false;return true}
function pageGate(page){const e=[];for(let i=0;i<page;i++)e.push(...pageErrors(i));return [...new Set(e)]}
function counter(kind,id,value){return `<div class="counter" data-kind="${kind}" data-id="${esc(id)}">${[-10,-5,-1].map(n=>`<button data-delta="${n}" aria-label="${esc(id)} ${n}">${n}</button>`).join('')}<input type="number" min="0" max="${kind==='proficiency'?75:65}" value="${value}" aria-label="${esc(id)} 數值">${[1,5,10].map(n=>`<button data-delta="${n}" aria-label="${esc(id)} 加 ${n}">+${n}</button>`).join('')}</div>`}
function render(){const page=$('#page');$('#title').textContent=`${String(s.page+1).padStart(2,'0')}｜${titles[s.page]}`;
 $('#tabs').innerHTML=titles.map((t,i)=>'<button data-tab="'+i+'" class="note-tab '+(i===s.page?'active':'')+'" aria-current="'+(i===s.page?'step':'false')+'"><span>'+String(i+1).padStart(2,'0')+'</span>'+t+'</button>').join('');
 let html='';switch(s.page){case 0:html=`<div class="identity"><div class="portrait">${s.appearance.portraitSource?`<img src="${s.appearance.portraitSource.previewUrl||s.appearance.portraitSource.dataUrl}" alt="角色頭像">`:'<div class="silhouette" aria-hidden="true">♟</div>'}<label class="field">上傳角色頭像<input id="portraitUpload" type="file" accept="image/png,image/jpeg,image/webp"></label></div><div class="formgrid"><div class="field wide"><label>姓名</label><input data-basic="name" value="${esc(s.basic.name)}"></div><div class="field wide"><label>生日 · 月／日</label><button type="button" id="openBirthday"><span id="birthdayValue">選擇月份與日期</span></button></div><div class="field"><label>性別</label><select data-basic="gender">${[['male','男性'],['female','女性'],['neutral','中性']].map(([v,l])=>`<option value="${v}" ${s.basic.gender===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="field"><label>代名詞</label><input data-basic="pronouns" value="${esc(s.basic.pronouns)}"></div></div></div>`;break;
 case 1:html='<div class="finance"><section><h2>家庭經濟狀況</h2><p class="note">五種結果等機率分配，每級 20%。首次投骰後立即綁定本局。</p>'+(run.locked?'<p>本局結果：<strong>'+esc(run.result.label)+'</strong></p>':'<p>尚未投骰</p>')+'<button type="button" id="financeRoll" '+(run.locked?'disabled':'')+'>投骰並鎖定</button><details><summary>Developer Mode</summary><label><input type="checkbox" id="devMode" '+(s.dev?'checked':'')+'> 開發者測試模式</label><div class="dev-pick" id="devPick" '+(s.dev?'':'hidden')+'></div><button type="button" id="devReroll" '+(s.dev?'':'hidden')+'>開發者重骰</button></details></section><section><h2>國籍／地區</h2><label class="field"><span>國籍／地區</span><input id="nationality" value="'+esc(s.nationality)+'"></label></section></div>';break;
 case 2:html='<p class="budget">剩餘能力值：<strong>'+attributePointsRemaining(s)+'</strong> / 250</p><details><summary>計算方式</summary>六項總值 250；單項創角上限 65。</details><div class="statgrid">'+attributes.map(id=>'<div class="stat"><b>'+id+'</b>'+counter('attribute',id,s.attributes[id])+'</div>').join('')+'</div>';break;
 case 3:html=`<div class="split"><div class="list" id="longList">${Object.entries(categories).map(([id,g])=>{const x=categoryStatus(s,id);const skillNames=id==='語言'?[...g.skills,...s.otherLanguages]:g.skills;return `<details class="category" data-group="${esc(id)}" ${s.openGroups[id]?'open':''}><summary>${id} <span class="meta ${x.remaining<0?'over':''}">${x.allocated} / ${x.total} · 剩餘 ${x.remaining}</span></summary><p class="meta">${x.pair.join(' + ')} + floor((${x.pair.join(' × ')}) / 100) · 總可用 ${x.total} · 已投入 ${x.allocated} · 剩餘 ${x.remaining}</p>${id==='語言'?`<label class="field">母語語種<input id="motherTongue" value="${esc(s.motherTongue)}"></label>`:''}${skillNames.map(name=>`<div class="skillrow"><button class="name" data-detail="${esc(name)}">${esc(name==='母語'&&s.motherTongue?`母語 · ${s.motherTongue}`:name)}</button>${counter('skill',name,s.skills[name]??0)}</div>`).join('')}${id==='語言'?'<button id="addLanguage">＋新增其他語種</button>':''}</details>`}).join('')}</div><aside class="details ${mobileDetail?'open':''}" id="detailPane"><button id="closeDetail">關閉</button><h2>${esc(detail||'技能詳情')}</h2><p>${detail?'此技能的詳細用途與檢定規則尚待正式定義。':'點選左側技能名稱查看。'}</p></aside></div>`;break;
 case 4:html=`<p class="budget">剩餘熟練度點數：<strong>${proficiencyRemaining(s)}</strong> / 500</p><div class="split"><div class="list" id="longList">${Object.entries(proficiencyGroups).map(([id,names])=>`<details class="category" data-progroup="${esc(id)}" ${s.openProficiencies[id]?'open':''}><summary>${id}</summary>${[...names,...(id==='其他具體熟練項目'?s.customProficiencies:[])].map(name=>`<div class="skillrow"><button class="name" data-detail="${esc(name)}">${esc(name)}</button>${counter('proficiency',name,s.proficiencies[name]||0)}</div>`).join('')}${id==='其他具體熟練項目'?'<button id="addProficiency">＋新增具體熟練項目</button>':''}</details>`).join('')}</div><aside class="details ${mobileDetail?'open':''}" id="detailPane"><button id="closeDetail">關閉</button><h2>${esc(detail||'熟練度詳情')}</h2><p>具體工具、技術或操作經驗；單項上限 75。</p></aside></div>`;break;
 case 5:html=`<div class="center"><label class="field"><span>過去經歷 · 選填</span><textarea id="experience" class="background" placeholder="在此自由書寫角色的過去經歷……">${esc(s.experience)}</textarea></label></div>`;break;
 case 6:{const filled=Object.entries(s.skills).filter(([k,v])=>v>(k==='母語'?55:0));const prof=Object.entries(s.proficiencies).filter(([,v])=>v>0);html='<div class="summary"><article><h2>基本資料</h2><p>'+esc(s.basic.name)+'</p><p>'+esc(s.basic.month)+' 月 '+esc(s.basic.day)+' 日</p><p>'+esc(s.basic.gender)+' · '+esc(s.basic.pronouns)+'</p></article><article><h2>家庭／經濟</h2><p>'+esc(run.result?.label||'未鎖定')+'</p><p>'+esc(s.nationality||'國籍／地區未填')+'</p><h2>Attributes</h2><p>'+attributes.map(id=>id+' '+s.attributes[id]).join(' · ')+'</p></article><article><h2>Skills</h2><p>已配置 '+filled.length+' 項</p><details><summary>查看完整技能</summary>'+filled.map(([k,v])=>'<p>'+esc(k)+' '+v+'</p>').join('')+'</details><h2>Proficiencies</h2><p>已配置 '+prof.length+' 項 · 剩餘 '+proficiencyRemaining(s)+'</p><details><summary>查看完整熟練度</summary>'+prof.map(([k,v])=>'<p>'+esc(k)+' '+v+'</p>').join('')+'</details><h2>Background</h2><p>'+(s.experience.trim()?'已填寫':'未填寫')+'</p>'+(s.experience.trim()?'<p>'+esc(s.experience)+'</p>':'')+'</article></div><p class="note">'+(pageErrors(6).map(esc).join('；')||'資料完整，可以確認。')+'</p>';break;}}
 page.innerHTML=html;const birthdayValue=$('#birthdayValue');if(birthdayValue&&s.basic.month&&s.basic.day)birthdayValue.textContent=s.basic.month+' 月 '+s.basic.day+' 日';$('#status').textContent=message;const portrait=matchMedia('(orientation: portrait) and (max-width: 900px) and (pointer: coarse)').matches;$('#rotateGate').hidden=!portrait;$('#creator').hidden=portrait;$('#back').disabled=s.page===0;$('#next').textContent=s.page===6?'確認角色資料':'下一頁';if(s.page===3||s.page===4)$('#longList').scrollTop=s.scroll[s.page===3?'skills':'proficiencies']||0;bind();}
function changePage(next){if(next<0||next>6)return;const g=pageGate(next);if(g.length){message=g.join('；');render();return}if(s.page===3||s.page===4)s.scroll[s.page===3?'skills':'proficiencies']=$('#longList').scrollTop;s.page=next;mobileDetail=false;message='';save();render()}
function bind(){all('[data-basic]').forEach(el=>el.oninput=()=>{s.basic[el.dataset.basic]=el.value;save()});$('#nationality')?.addEventListener('input',e=>{s.nationality=e.target.value;save()});$('#experience')?.addEventListener('input',e=>{s.experience=e.target.value;save()});
 all('.counter').forEach(row=>{const {kind,id}=row.dataset,input=row.querySelector('input');const set=(v,delta=false)=>{try{if(delta)adjust(s,kind,id,v);else allocate(s,kind,id,v);message='';save()}catch(e){message=e.message}input.value=kind==='attribute'?s.attributes[id]:kind==='skill'?s.skills[id]||0:s.proficiencies[id]||0;$('#status').textContent=message;if(kind==='skill'||kind==='attribute'||kind==='proficiency'){const pos=$('#longList')?.scrollTop;render();if($('#longList')&&pos!=null)$('#longList').scrollTop=pos}};input.onchange=()=>set(Number(input.value));row.querySelectorAll('[data-delta]').forEach(b=>b.onclick=()=>set(Number(b.dataset.delta),true))});
 all('.category').forEach(d=>d.ontoggle=()=>{s.openGroups[d.dataset.group]=d.open;save()});all('[data-progroup]').forEach(d=>d.ontoggle=()=>{s.openProficiencies[d.dataset.progroup]=d.open;save()});$('#longList')?.addEventListener('scroll',e=>{s.scroll[s.page===3?'skills':'proficiencies']=e.target.scrollTop;save()},{passive:true});
 all('[data-detail]').forEach(b=>b.onclick=()=>{detail=b.dataset.detail;mobileDetail=true;$('#detailPane').classList.add('open');$('#detailPane h2').textContent=detail});$('#closeDetail')?.addEventListener('click',()=>{$('#detailPane').classList.remove('open');mobileDetail=false});
 $('#motherTongue')?.addEventListener('change',e=>{const value=e.target.value.trim();if(s.otherLanguages.some(x=>x.toLowerCase()===value.toLowerCase())){message='母語不能與其他語種重複';render();return}s.motherTongue=value;save();render()});$('#addLanguage')?.addEventListener('click',()=>{const name=prompt('輸入其他語種');if(!name)return;const value=name.trim();if(!value||s.motherTongue.toLowerCase()===value.toLowerCase()||s.otherLanguages.some(x=>x.toLowerCase()===value.toLowerCase())){message='語種不可重複';render();return}s.otherLanguages.push(value);s.skillCategory[value]='語言';save();render()});$('#addProficiency')?.addEventListener('click',()=>{const name=prompt('輸入具體熟練項目（不可建立新技能）')?.trim();if(!name)return;if(Object.values(categories).some(x=>x.skills.includes(name))||Object.values(proficiencyGroups).flat().includes(name)||s.customProficiencies.includes(name)){message='名稱重複或為正式技能';render();return}s.customProficiencies.push(name);save();render()});
 // No school UI in this seven-page Creator.
 $('#financeRoll')?.addEventListener('click',()=>{run=rollFinance();message='本局家庭經濟已鎖定';render()});$('#devMode')?.addEventListener('change',e=>{s.dev=e.target.checked;save();render()});if($('#devPick'))$('#devPick').innerHTML=financeTiers.map(t=>'<button type="button" data-tier="'+t.id+'">'+t.label+'</button>').join('');all('[data-tier]').forEach(b=>b.onclick=()=>{if(s.dev){run=developerFinance(localStorage,{tierId:b.dataset.tier});message='開發測試：'+run.result.label;render()}});$('#devReroll')?.addEventListener('click',()=>{if(s.dev){localStorage.removeItem('clearwater-life-run-finance-v2');run=newRun();render()}});$('#openBirthday')?.addEventListener('click',openBirthdayPicker);
 $('#portraitUpload')?.addEventListener('change',portraitUpload);$('#portraitButton')?.addEventListener('click',()=>$('#portraitUpload').click());
}
$('#tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(!b)return;b.classList.add('pressed');setTimeout(()=>{b.classList.remove('pressed');const n=+b.dataset.tab,g=pageGate(n);if(g.length){message=g.join('；');render()}else changePage(n)},190)};$('#back').onclick=()=>changePage(s.page-1);$('#next').onclick=()=>{if(s.page<6){const e=pageErrors(s.page);if(e.length){message=e.join('；');render();return}changePage(s.page+1);return}try{confirmCharacterData(s,run);s.confirmed=true;save();message='角色資料已確認。本輪 Character Creator 到此結束。';$('#status').textContent=message;$('#next').disabled=true}catch(e){message=e.message;$('#status').textContent=message}};

function openBirthdayPicker(){const d=$('#birthdayDialog'),m=$('#birthMonth'),day=$('#birthDay');m.value=s.basic.month||'';const fill=()=>{const n=Number(m.value),max=n?[31,29,31,30,31,30,31,31,30,31,30,31][n-1]:0;day.innerHTML='<option value="">選擇日期</option>'+Array.from({length:max},(_,i)=>'<option value="'+(i+1)+'">'+(i+1)+' 日</option>').join('');day.disabled=!n;if(String(n)===String(s.basic.month))day.value=s.basic.day||''};fill();m.onchange=fill;$('#saveBirthday').onclick=()=>{if(!m.value||!day.value)return;s.basic.month=m.value;s.basic.day=day.value;save();d.close();render()};d.showModal()}
let imageUrl='',frame={x:.2,y:.15,w:.6,h:.7},imageScale=1,active=null;
const stage=$('#cropStage'),crop=$('#cropFrame');function drawCrop(){crop.style.left=frame.x*100+'%';crop.style.top=frame.y*100+'%';crop.style.width=frame.w*100+'%';crop.style.height=frame.h*100+'%';$('#cropImage').style.transform=`scale(${imageScale})`}
function portraitUpload(e){const file=e.target.files[0];if(!file||!['image/png','image/jpeg','image/webp'].includes(file.type))return;const reader=new FileReader();reader.onload=()=>{imageUrl=reader.result;$('#cropImage').src=imageUrl;frame={x:.2,y:.15,w:.6,h:.7};imageScale=1;$('#zoom').value='1';drawCrop();$('#cropDialog').showModal()};reader.readAsDataURL(file)}
const handles=['nw','n','ne','e','se','s','sw','w'];crop.innerHTML=handles.map((h,i)=>`<i data-handle="${h}" style="left:${[0,50,100,100,100,50,0,0][i]}%;top:${[0,0,0,50,100,100,100,50][i]}%;cursor:${h}-resize"></i>`).join('');
crop.onpointerdown=e=>{e.preventDefault();active={handle:e.target.dataset.handle||'move',x:e.clientX,y:e.clientY,start:{...frame}};crop.setPointerCapture(e.pointerId)};crop.onpointermove=e=>{if(!active)return;const dx=(e.clientX-active.x)/stage.clientWidth,dy=(e.clientY-active.y)/stage.clientHeight,f={...active.start},h=active.handle;if(h==='move'){f.x=Math.max(0,Math.min(1-f.w,f.x+dx));f.y=Math.max(0,Math.min(1-f.h,f.y+dy))}else{if(h.includes('w')){f.x=Math.max(0,Math.min(f.x+f.w-.08,f.x+dx));f.w=active.start.x+active.start.w-f.x}if(h.includes('e'))f.w=Math.max(.08,Math.min(1-f.x,f.w+dx));if(h.includes('n')){f.y=Math.max(0,Math.min(f.y+f.h-.08,f.y+dy));f.h=active.start.y+active.start.h-f.y}if(h.includes('s'))f.h=Math.max(.08,Math.min(1-f.y,f.h+dy))}frame=f;drawCrop()};crop.onpointerup=()=>active=null;crop.onpointercancel=()=>active=null;$('#zoom').oninput=e=>{imageScale=+e.target.value;drawCrop()};stage.onwheel=e=>{e.preventDefault();imageScale=Math.max(1,Math.min(3,imageScale+(e.deltaY<0?.05:-.05)));$('#zoom').value=imageScale;drawCrop()};let pinch=null;stage.addEventListener('touchmove',e=>{if(e.touches.length===2){e.preventDefault();const distance=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(pinch)imageScale=Math.max(1,Math.min(3,imageScale*distance/pinch));pinch=distance;$('#zoom').value=imageScale;drawCrop()}},{passive:false});stage.addEventListener('touchend',()=>pinch=null);$('#resetCrop').onclick=()=>{frame={x:.2,y:.15,w:.6,h:.7};imageScale=1;$('#zoom').value=1;drawCrop()};$('#confirmCrop').onclick=()=>{const img=$('#cropImage'),canvas=document.createElement('canvas'),scale=Math.min(stage.clientWidth/img.naturalWidth,stage.clientHeight/img.naturalHeight)*imageScale,drawW=img.naturalWidth*scale,drawH=img.naturalHeight*scale,offsetX=(stage.clientWidth-drawW)/2,offsetY=(stage.clientHeight-drawH)/2,sx=Math.max(0,Math.min(img.naturalWidth-1,(frame.x*stage.clientWidth-offsetX)/scale)),sy=Math.max(0,Math.min(img.naturalHeight-1,(frame.y*stage.clientHeight-offsetY)/scale)),sw=Math.max(1,Math.min(img.naturalWidth-sx,frame.w*stage.clientWidth/scale)),sh=Math.max(1,Math.min(img.naturalHeight-sy,frame.h*stage.clientHeight/scale));canvas.width=Math.round(sw);canvas.height=Math.round(sh);canvas.getContext('2d').drawImage(img,sx,sy,sw,sh,0,0,canvas.width,canvas.height);s.appearance.portraitSource={kind:'uploaded-image',dataUrl:imageUrl,previewUrl:canvas.toDataURL('image/png'),rect:{x:sx/img.naturalWidth,y:sy/img.naturalHeight,width:sw/img.naturalWidth,height:sh/img.naturalHeight}};save();$('#cropDialog').close();render()};render();
window.addEventListener('orientationchange',render);window.addEventListener('resize',render);
