import {newCharacter,validateCharacter,finishCharacter} from '../creation-v2/creator-service.mjs';
import {attributes,categories,proficiencyGroups,schools,rules} from '../creation-v2/catalog.mjs';
import {allocate} from '../creation-v2/allocation-engine.mjs';
import {categoryStatus,proficiencyRemaining} from '../creation-v2/point-source-ledger.mjs';
import {schoolEligibility} from '../creation-v2/school-eligibility.mjs';
import {readRun,newRun,rollFinance,developerFinance} from '../creation-v2/finance.mjs';
const $=q=>document.querySelector(q),all=q=>[...document.querySelectorAll(q)],KEY='clearwater-life-creator-v3';
let s;try{s=JSON.parse(localStorage.getItem(KEY))||newCharacter();if(s.version!==3)s=newCharacter()}catch{s=newCharacter()}
let run=readRun()||newRun();let message='',detail='',mobileDetail=false;
const titles=['基本資料','家庭／經濟狀況','Attributes 能力值','Skills 技能','Proficiencies 熟練度','Background 過去經歷','選校','最終確認'];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(s))}
function canEnter(page){return page<=6||!!run.locked}
function counter(kind,id,value){return `<div class="counter" data-kind="${kind}" data-id="${esc(id)}">${[-10,-5,-1].map(n=>`<button data-delta="${n}" aria-label="${esc(id)} ${n}">${n}</button>`).join('')}<input type="number" min="0" max="${kind==='proficiency'?75:65}" value="${value}" aria-label="${esc(id)} 數值">${[1,5,10].map(n=>`<button data-delta="${n}" aria-label="${esc(id)} 加 ${n}">+${n}</button>`).join('')}</div>`}
function render(){const page=$('#page');$('#title').textContent=`${String(s.page+1).padStart(2,'0')}｜${titles[s.page]}`;
 $('#tabs').innerHTML=titles.map((t,i)=>`<button data-tab="${i}" ${canEnter(i)?'':'disabled'} class="${i===s.page?'active':''}">${String(i+1).padStart(2,'0')}<br>${t.split(' ')[0]}</button>`).join('');
 let html='';switch(s.page){case 0:html=`<div class="identity"><div class="portrait">${s.appearance.portraitSource?`<img src="${s.appearance.portraitSource.dataUrl}" alt="角色頭像">`:'<div class="silhouette" aria-hidden="true">♟</div>'}<label class="field">上傳角色頭像<input id="portraitUpload" type="file" accept="image/png,image/jpeg,image/webp"></label></div><div class="formgrid"><div class="field wide"><label>姓名</label><input data-basic="name" value="${esc(s.basic.name)}"></div><div class="field"><label>生日 · 月</label><input data-basic="month" type="number" min="1" max="12" value="${esc(s.basic.month)}"></div><div class="field"><label>生日 · 日</label><input data-basic="day" type="number" min="1" max="31" value="${esc(s.basic.day)}"></div><div class="field"><label>性別</label><select data-basic="gender">${[['male','男性'],['female','女性'],['neutral','中性']].map(([v,l])=>`<option value="${v}" ${s.basic.gender===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="field"><label>代名詞</label><input data-basic="pronouns" value="${esc(s.basic.pronouns)}"></div></div></div>`;break;
 case 1:html=`<div class="finance"><section><h2>家庭經濟</h2><p class="note">結果與本局綁定；家庭資源不等於玩家錢包。</p>${run.locked?`<p>已鎖定：${esc(run.result.label||run.result.tierId)}</p>`:'<p>尚未投骰</p>'}<button id="financeRoll" ${run.locked?'disabled':''}>投骰並鎖定本局結果</button><p class="note">正式機率尚未在 CYW-51 定稿。一般模式暫停投骰，避免產生未授權的正式結果。</p><details><summary>開發者測試</summary><input id="devTier" placeholder="測試層級 ID"><button id="devSet">設定測試結果</button></details></section><section><h2>國籍／地區</h2><label class="field"><span>國籍／地區</span><input id="nationality" value="${esc(s.nationality)}"></label></section></div>`;break;
 case 2:html=`<p class="budget">剩餘能力值：<strong>${350-attributes.reduce((n,id)=>n+s.attributes[id],0)}</strong> / 350</p><details><summary>計算方式</summary>六項總值 350；單項創角上限 65。技能大項預算依兩項能力值計算。</details><div class="statgrid">${attributes.map(id=>`<div class="stat"><b>${id}</b>${counter('attribute',id,s.attributes[id])}</div>`).join('')}</div>`;break;
 case 3:html=`<div class="split"><div class="list" id="longList">${Object.entries(categories).map(([id,g])=>{const x=categoryStatus(s,id);const skillNames=id==='語言'?[...g.skills,...s.otherLanguages]:g.skills;return `<details class="category" data-group="${esc(id)}" ${s.openGroups[id]?'open':''}><summary>${id} <span class="meta ${x.remaining<0?'over':''}">${x.allocated} / ${x.total} · 剩餘 ${x.remaining}</span></summary><p class="meta">${x.pair.join(' + ')} + floor((${x.pair.join(' × ')}) / 100) · 總可用 ${x.total} · 已投入 ${x.allocated} · 剩餘 ${x.remaining}</p>${id==='語言'?`<label class="field">母語語種<input id="motherTongue" value="${esc(s.motherTongue)}"></label>`:''}${skillNames.map(name=>`<div class="skillrow"><button class="name" data-detail="${esc(name)}">${esc(name==='母語'&&s.motherTongue?`母語 · ${s.motherTongue}`:name)}</button>${counter('skill',name,s.skills[name]??0)}</div>`).join('')}${id==='語言'?'<button id="addLanguage">＋新增其他語種</button>':''}</details>`}).join('')}</div><aside class="details ${mobileDetail?'open':''}" id="detailPane"><button id="closeDetail">關閉</button><h2>${esc(detail||'技能詳情')}</h2><p>${detail?'此技能的詳細用途與檢定規則尚待正式定義。':'點選左側技能名稱查看。'}</p></aside></div>`;break;
 case 4:html=`<p class="budget">剩餘熟練度點數：<strong>${proficiencyRemaining(s)}</strong> / 500</p><div class="split"><div class="list" id="longList">${Object.entries(proficiencyGroups).map(([id,names])=>`<details class="category" data-progroup="${esc(id)}" ${s.openProficiencies[id]?'open':''}><summary>${id}</summary>${[...names,...(id==='其他具體熟練項目'?s.customProficiencies:[])].map(name=>`<div class="skillrow"><button class="name" data-detail="${esc(name)}">${esc(name)}</button>${counter('proficiency',name,s.proficiencies[name]||0)}</div>`).join('')}${id==='其他具體熟練項目'?'<button id="addProficiency">＋新增具體熟練項目</button>':''}</details>`).join('')}</div><aside class="details ${mobileDetail?'open':''}" id="detailPane"><button id="closeDetail">關閉</button><h2>${esc(detail||'熟練度詳情')}</h2><p>具體工具、技術或操作經驗；單項上限 75。</p></aside></div>`;break;
 case 5:html=`<div class="center"><label class="field"><span>過去經歷 · 選填</span><textarea id="experience" class="background" placeholder="在此自由書寫角色的過去經歷……">${esc(s.experience)}</textarea></label></div>`;break;
 case 6:html=`<div class="schoolgrid">${Object.entries(schools).map(([id,name])=>{const e=schoolEligibility(s,id,run);return `<article class="school ${e.ok?'':'unavailable'}"><div class="crest">校徽預留位置</div><h2>${esc(name)}</h2><p>${id==='coed'?'男女混合高中':id==='girls'?'女子學院':'男子學院'}</p><p class="note">${esc(e.why)}</p>${s.school===id?'<strong class="stamp">已選</strong>':''}<button data-school="${id}" ${e.ok?'':'disabled'}>選擇</button></article>`}).join('')}</div><p class="note">住宿、House 與走讀安排於入世後的準備週處理。</p>`;break;
 case 7:{const filled=Object.entries(s.skills).filter(([k,v])=>v>(k==='母語'?55:0));const prof=Object.entries(s.proficiencies).filter(([,v])=>v>0);html=`<div class="summary"><article><h2>A · 基本資料</h2><p>${esc(s.basic.name||'未填姓名')}</p><p>${esc(s.basic.month)}/${esc(s.basic.day)} · ${esc(s.basic.gender)}</p><p>背景：${s.experience.trim()?'已填寫':'未填寫'}</p></article><article><h2>B · 能力值與技能</h2><p>${attributes.map(id=>`${id} ${s.attributes[id]}`).join(' · ')}</p><p>已投入技能：${filled.length} 項</p><details><summary>查看完整技能</summary>${filled.map(([k,v])=>`<p>${esc(k)} ${v}</p>`).join('')}</details></article><article><h2>C · 熟練度、家庭與學校</h2><p>熟練度：${prof.length} 項</p><details><summary>查看完整熟練度</summary>${prof.map(([k,v])=>`<p>${esc(k)} ${v}</p>`).join('')}</details><p>家庭經濟：${esc(run.result?.label||'未鎖定')}</p><div class="crest">校徽預留位置</div><p>${esc(schools[s.school]||'未選校')}</p></article></div><p class="note">${validateCharacter(s,run).map(esc).join('；')||'可建立角色'}</p>`;break;}}
 page.innerHTML=html;$('#status').textContent=message;$('#back').disabled=s.page===0;$('#next').textContent=s.page===7?'確認建立角色':'下一頁';if(s.page===3||s.page===4)$('#longList').scrollTop=s.scroll[s.page===3?'skills':'proficiencies']||0;bind();}
function changePage(next){if(next<0||next>7||!canEnter(next)){message='請先鎖定家庭經濟結果。';render();return}if(s.page===3||s.page===4)s.scroll[s.page===3?'skills':'proficiencies']=$('#longList').scrollTop;s.page=next;mobileDetail=false;message='';save();render()}
function bind(){all('[data-basic]').forEach(el=>el.oninput=()=>{s.basic[el.dataset.basic]=el.value;save()});$('#nationality')?.addEventListener('input',e=>{s.nationality=e.target.value;save()});$('#experience')?.addEventListener('input',e=>{s.experience=e.target.value;save()});
 all('.counter').forEach(row=>{const {kind,id}=row.dataset;const input=row.querySelector('input');const set=value=>{try{allocate(s,kind,id,value);message='';save()}catch(e){message=e.message}input.value=kind==='attribute'?s.attributes[id]:kind==='skill'?s.skills[id]||0:s.proficiencies[id]||0;$('#status').textContent=message;if(kind==='skill'||kind==='attribute'||kind==='proficiency'){let pos=$('#longList')?.scrollTop;render();if($('#longList')&&pos!=null)$('#longList').scrollTop=pos}};input.onchange=()=>set(Number(input.value));row.querySelectorAll('[data-delta]').forEach(b=>b.onclick=()=>set(Number(input.value)+Number(b.dataset.delta)))});
 all('.category').forEach(d=>d.ontoggle=()=>{s.openGroups[d.dataset.group]=d.open;save()});all('[data-progroup]').forEach(d=>d.ontoggle=()=>{s.openProficiencies[d.dataset.progroup]=d.open;save()});$('#longList')?.addEventListener('scroll',e=>{s.scroll[s.page===3?'skills':'proficiencies']=e.target.scrollTop;save()},{passive:true});
 all('[data-detail]').forEach(b=>b.onclick=()=>{detail=b.dataset.detail;mobileDetail=true;$('#detailPane').classList.add('open');$('#detailPane h2').textContent=detail});$('#closeDetail')?.addEventListener('click',()=>{$('#detailPane').classList.remove('open');mobileDetail=false});
 $('#motherTongue')?.addEventListener('change',e=>{const value=e.target.value.trim();if(s.otherLanguages.some(x=>x.toLowerCase()===value.toLowerCase())){message='母語不能與其他語種重複';render();return}s.motherTongue=value;save();render()});$('#addLanguage')?.addEventListener('click',()=>{const name=prompt('輸入其他語種');if(!name)return;const value=name.trim();if(!value||s.motherTongue.toLowerCase()===value.toLowerCase()||s.otherLanguages.some(x=>x.toLowerCase()===value.toLowerCase())){message='語種不可重複';render();return}s.otherLanguages.push(value);s.skillCategory[value]='語言';save();render()});$('#addProficiency')?.addEventListener('click',()=>{const name=prompt('輸入具體熟練項目（不可建立新技能）')?.trim();if(!name)return;if(Object.values(categories).some(x=>x.skills.includes(name))||Object.values(proficiencyGroups).flat().includes(name)||s.customProficiencies.includes(name)){message='名稱重複或為正式技能';render();return}s.customProficiencies.push(name);save();render()});
 all('[data-school]').forEach(b=>b.onclick=()=>{if(schoolEligibility(s,b.dataset.school,run).ok){s.school=b.dataset.school;save();render()}});
 $('#financeRoll')?.addEventListener('click',()=>{try{run=rollFinance();message=''}catch(e){message=e.message}render()});$('#devSet')?.addEventListener('click',()=>{const tierId=$('#devTier').value.trim();if(tierId){run=developerFinance(localStorage,{tierId,label:`測試結果：${tierId}`});render()}});
 $('#portraitUpload')?.addEventListener('change',portraitUpload);
}
$('#tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(b)changePage(+b.dataset.tab)};$('#back').onclick=()=>changePage(s.page-1);$('#next').onclick=()=>{if(s.page<7){changePage(s.page+1);return}try{const state=finishCharacter(s,run);localStorage.setItem('clearwater-life-player-state-v1',JSON.stringify(state));localStorage.setItem('clearwater-life-game-v2',JSON.stringify(state));message='角色已建立，進入開學前準備週。';$('#status').textContent=message;$('#next').disabled=true}catch(e){message=e.message;$('#status').textContent=message}};
let imageUrl='',frame={x:.2,y:.15,w:.6,h:.7},imageScale=1,active=null;
const stage=$('#cropStage'),crop=$('#cropFrame');function drawCrop(){crop.style.left=frame.x*100+'%';crop.style.top=frame.y*100+'%';crop.style.width=frame.w*100+'%';crop.style.height=frame.h*100+'%';$('#cropImage').style.transform=`scale(${imageScale})`}
function portraitUpload(e){const file=e.target.files[0];if(!file||!['image/png','image/jpeg','image/webp'].includes(file.type))return;const reader=new FileReader();reader.onload=()=>{imageUrl=reader.result;$('#cropImage').src=imageUrl;frame={x:.2,y:.15,w:.6,h:.7};imageScale=1;$('#zoom').value='1';drawCrop();$('#cropDialog').showModal()};reader.readAsDataURL(file)}
const handles=['nw','n','ne','e','se','s','sw','w'];crop.innerHTML=handles.map((h,i)=>`<i data-handle="${h}" style="left:${[0,50,100,100,100,50,0,0][i]}%;top:${[0,0,0,50,100,100,100,50][i]}%;cursor:${h}-resize"></i>`).join('');
crop.onpointerdown=e=>{e.preventDefault();active={handle:e.target.dataset.handle||'move',x:e.clientX,y:e.clientY,start:{...frame}};crop.setPointerCapture(e.pointerId)};crop.onpointermove=e=>{if(!active)return;const dx=(e.clientX-active.x)/stage.clientWidth,dy=(e.clientY-active.y)/stage.clientHeight,f={...active.start},h=active.handle;if(h==='move'){f.x=Math.max(0,Math.min(1-f.w,f.x+dx));f.y=Math.max(0,Math.min(1-f.h,f.y+dy))}else{if(h.includes('w')){f.x=Math.max(0,Math.min(f.x+f.w-.08,f.x+dx));f.w=active.start.x+active.start.w-f.x}if(h.includes('e'))f.w=Math.max(.08,Math.min(1-f.x,f.w+dx));if(h.includes('n')){f.y=Math.max(0,Math.min(f.y+f.h-.08,f.y+dy));f.h=active.start.y+active.start.h-f.y}if(h.includes('s'))f.h=Math.max(.08,Math.min(1-f.y,f.h+dy))}frame=f;drawCrop()};crop.onpointerup=()=>active=null;crop.onpointercancel=()=>active=null;$('#zoom').oninput=e=>{imageScale=+e.target.value;drawCrop()};stage.onwheel=e=>{e.preventDefault();imageScale=Math.max(1,Math.min(3,imageScale+(e.deltaY<0?.05:-.05)));$('#zoom').value=imageScale;drawCrop()};let pinch=null;stage.addEventListener('touchmove',e=>{if(e.touches.length===2){e.preventDefault();const distance=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(pinch)imageScale=Math.max(1,Math.min(3,imageScale*distance/pinch));pinch=distance;$('#zoom').value=imageScale;drawCrop()}},{passive:false});stage.addEventListener('touchend',()=>pinch=null);$('#resetCrop').onclick=()=>{frame={x:.2,y:.15,w:.6,h:.7};imageScale=1;$('#zoom').value=1;drawCrop()};$('#confirmCrop').onclick=()=>{s.appearance.portraitSource={kind:'uploaded-image',dataUrl:imageUrl,rect:{...frame},zoom:imageScale};save();$('#cropDialog').close();render()};render();
