import {residentialSide,assignResidence} from "../ravenwood/engine.mjs";
const $=s=>document.querySelector(s), KEY="cbl-character-v01";
const steps=["基本資料","能力值","學科技能","其他技能","家庭／經歷","選校","住宿","確認"];
let s=JSON.parse(localStorage.getItem(KEY)||"null")||{page:0,basic:{name:"",birthday:"09/01",gender:"中性",pronouns:""},attr:{STR:30,CON:30,AGI:30,DEX:30,PER:30,INT:30},academic:{},skills:{},family:{finance:"富裕",notes:""},experience:"",school:"",house:"",residence:"",dev:false,openGroups:{}};
s.openGroups=s.openGroups||{};
const academics=["語文","English","Spanish","French","Japanese","Mandarin Chinese","數學","物理","化學","生物","歷史","地理","政治／公民","經濟","法律","心理"];
const groups={ "視覺藝術與設計":["繪畫","雕塑／立體造型","攝影","設計"],"音樂與表演":["音樂","表演","舞蹈"],"媒體製作":["影像製作","音訊製作"],"資訊與數位技術":["電腦","程式設計","資料分析"],"工程、製作與修繕":["工程","電子","機械","修理","木工","縫紉","手工藝"],"生活與實用":["烹飪","家務","園藝","急救","生存","駕駛"],"體育與身體技術":["跑步","游泳","自行車","滑行","籃球","足球","排球","棒球／壘球","網球","羽毛球","拳擊","跆拳道","空手道","柔道","體操","滑雪"],"溝通與社會互動":["演說","辯論","交涉","欺瞞","洞察"],"世界玩法":["潛行","妙手"]};
const schools={coed:["Ravenwood High School","雷文伍德高中"],girls:["Rosamund Girls’ Academy","羅莎蒙德女子學院"],boys:["Avenor Boys’ Academy","阿維諾男子學院"]};
const houses=["Valette 瓦萊特","Quillan 奎蘭特","Fairmont 費爾蒙特","Hartwell 哈特威爾"];
function esc(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function save(){localStorage.setItem(KEY,JSON.stringify(s))}
function points(obj){return Object.values(obj).reduce((a,b)=>a+(+b||0),0)}
function counter(name,val,kind){return '<div class="row"><span>'+name+'</span><div class="counter"><button data-minus="'+kind+'|'+name+'">−</button><input class="score-input" type="number" min="0" max="75" inputmode="numeric" data-score="'+kind+'|'+name+'" value="'+val+'"><button data-plus="'+kind+'|'+name+'">＋</button></div></div>'}
function randomize(kind,names,max=75){const obj=s[kind];names.forEach(name=>obj[name]=Math.floor(Math.random()*(max+1)));save();render()}
function eligibleSchool(id){const g=s.basic.gender,f=s.family.finance;if(id==="coed")return {ok:true,why:"公立混校，可申請"};if(id==="girls"){if(g==="男性")return {ok:false,why:"目前性別資料不符合女子學院入學資格"};if(f!=="富裕")return {ok:false,why:"目前家庭財政未達私校一般入學條件"};return {ok:true,why:"符合目前測試資格"}}if(id==="boys"){if(g==="女性")return {ok:false,why:"目前性別資料不符合男子學院入學資格"};if(f!=="富裕")return {ok:false,why:"目前家庭財政未達私校一般入學條件"};return {ok:true,why:"符合目前測試資格"}}return {ok:false,why:"不符合資格"}}
function nav(){ $("#steps").innerHTML=steps.map((x,i)=>'<button data-go="'+i+'" class="'+(i===s.page?'active':'')+'">'+(i+1)+'. '+x+'</button>').join("");$("#bar").style.width=((s.page+1)/steps.length*100)+"%";$("#back").style.visibility=s.page?"visible":"hidden";$("#next").textContent=s.page===7?s.school==="coed"?"建立角色並進入 Ravenwood":"建立 Player State":"下一步 ›"}
function render(){
 nav();let h="";
 if(s.page===0)h='<div class="hero"><div class="portrait"><span>測試頭貼<br>portrait asset</span></div><div><h2>你是誰？</h2><p>第一版只建立必要資料；正式捏臉之後再接入同一份 Player State。</p></div></div><div class="card"><label class="field">姓名<input data-basic="name" value="'+esc(s.basic.name)+'"></label><label class="field">生日（月／日）<input data-basic="birthday" value="'+esc(s.basic.birthday)+'" placeholder="09/01"></label><div class="field">性別<div class="choices">'+["男性","女性","中性"].map(x=>'<button data-gender="'+x+'" class="'+(s.basic.gender===x?'selected':'')+'">'+x+'</button>').join("")+'</div></div><label class="field">代名詞<input data-basic="pronouns" value="'+esc(s.basic.pronouns)+'" placeholder="可自訂"></label></div>';
 if(s.page===1){let total=Object.values(s.attr).reduce((a,b)=>a+b,0);h='<h2>Attribute <small>能力值</small></h2><p class="hint">v0.1 先保存六項能力；對技能與學習效率的公式之後再定。</p><div class="stats"><div class="stat"><small>目前總值</small><b>'+total+'</b></div><div class="stat"><small>項目</small><b>6</b></div><div class="stat"><small>公式</small><b>—</b></div></div><div class="dev"><span>快速產生能力值</span><button id="rollAttr">🎲 Random Roll 隨機骰</button></div><div class="card">'+Object.keys(s.attr).map(k=>counter(k,s.attr[k],"attr")).join("")+'</div>'}
 if(s.page===2){let used=points(s.academic);h='<h2>Academic Skills <small>學科技能</small></h2><div class="stats"><div class="stat"><small>已投入</small><b>'+used+'</b></div><div class="stat"><small>單項上限</small><b>75</b></div><div class="stat"><small>私人測試</small><b>寬裕</b></div></div><div class="dev"><span>快速產生學科技能</span><button id="rollAcademic">🎲 Random Roll 隨機骰</button></div><div class="dev"><span>Developer Override 開發者覆寫</span><input id="dev" type="checkbox" '+(s.dev?'checked':'')+'></div><div class="card">'+academics.map(k=>counter(k,s.academic[k]||0,"academic")).join("")+'</div>'}
 if(s.page===3){let used=points(s.skills);h='<h2>Other Skills <small>其他技能</small></h2><p class="hint">Skill Group（技能群）只有分類，不存在「美術 70」或「體育 70」總值。</p><div class="stats"><div class="stat"><small>已投入</small><b>'+used+'</b></div><div class="stat"><small>單項上限</small><b>75</b></div><div class="stat"><small>群組</small><b>'+Object.keys(groups).length+'</b></div></div><div class="dev"><span>快速產生其他技能</span><button id="rollSkills">🎲 Random Roll 隨機骰</button></div>'+Object.entries(groups).map(([g,a])=>'<details class="group" data-group="'+g+'" '+(s.openGroups[g]?'open':'')+'><summary>'+g+'</summary><div class="inside">'+a.map(k=>counter(k,s.skills[k]||0,"skills")).join("")+'</div></details>').join("")}
 if(s.page===4)h='<h2>家庭與過去經歷</h2><div class="card"><label class="field">Family Finance / 家庭經濟<select id="finance"><option>一般</option><option>中產</option><option>中上產</option><option>富裕</option></select></label><label class="field">家庭備註<textarea data-family="notes" rows="4">'+esc(s.family.notes)+'</textarea></label></div><div class="card"><h3>Past Experience / 過去經歷</h3><p class="hint">能力描述結果；故事解釋來源。可以拒絕系統建議、改寫或完全自填。</p><label class="field">角色在入學前經歷<textarea id="experience" rows="8" placeholder="例如：家人要求我學了八年鋼琴，我本人並不喜歡。">'+esc(s.experience)+'</textarea></label></div>';
 if(s.page===5)h='<h2>Choose School <small>選校</small></h2><p class="hint">依性別與 Family Finance（家庭財政）顯示目前可選學校；不符合者會保留顯示並標明原因。</p>'+Object.entries(schools).map(([id,x])=>{const e=eligibleSchool(id);return '<button class="school '+(s.school===id?'selected ':'')+(e.ok?'':'blocked')+'" data-school="'+id+'" '+(e.ok?'':'disabled')+'><b>'+x[0]+'</b><small>'+x[1]+' · '+e.why+'</small></button>'}).join("")+(s.school==="girls"?'<div class="card"><h3>Rosamund House / 學院</h3><div class="choices">'+houses.map(x=>'<button data-house="'+x+'" class="'+(s.house===x?'selected':'')+'">'+x+'</button>').join("")+'</div></div>':"");
 if(s.page===6){let txt=s.school==="girls"?"四年校內住宿；住所由學院宿舍系統分配。":s.school==="coed"?"高一校內住宿；後續年級依規則處理。":"Avenor 不強制住宿，可選校內或校外。";h='<h2>Residence <small>住宿</small></h2><div class="card"><h3>'+(schools[s.school]?.[1]||"尚未選校")+'</h3><p class="hint">'+txt+'</p>'+(s.school==="boys"?'<div class="choices"><button data-res="campus" class="'+(s.residence==="campus"?'selected':'')+'">校內住宿</button><button data-res="offcampus" class="'+(s.residence==="offcampus"?'selected':'')+'">校外住宿</button></div>':'')+'</div>';if(s.school==="coed"){const side=residentialSide(s.basic.gender,s.residentialAccess);h+='<div class="card"><h3>住宿側分配</h3>'+(s.basic.gender==="中性"?'<p class="hint">請選擇希望入住的住宿側。</p><div class="choices">'+[["male_side","男生住宿側"],["female_side","女生住宿側"]].map(([id,label])=>'<button data-side="'+id+'" class="'+(side===id?'selected':'')+'">'+label+'</button>').join("")+'</div>':'<p>'+(side==="male_side"?"固定分配男生住宿側":"固定分配女生住宿側")+'</p>')+'<p class="hint">08／10 男側，09／11 女側。第一版分配至對應側的第一棟、201 雙人房。</p></div>';}}
 if(s.page===7){const out={saveVersion:1,player:{identity:s.basic,portraitId:"placeholder-v01",attributes:s.attr,academicSkills:s.academic,skills:s.skills,family:s.family,pastExperience:s.experience,schoolId:s.school,houseId:s.house||null,residenceChoice:s.residence||null,residentialAccess:s.school==="coed"?residentialSide(s.basic.gender,s.residentialAccess):null},interfaces:{appearance:{},bodyTraits:{},proficiencies:{},knowledge:{}}};h='<h2>確認角色</h2><p class="hint">這就是第一版準備寫入正式 Game / Player State 的資料。</p><div class="card summary"><b>'+esc(s.basic.name||"未命名角色")+'</b><p>'+s.basic.gender+' · '+esc(s.basic.birthday)+' · '+(schools[s.school]?.[1]||"未選校")+'</p><span class="tag">Academic '+points(s.academic)+'</span><span class="tag">Skills '+points(s.skills)+'</span><span class="tag">Skill cap 75</span><pre>'+esc(JSON.stringify(out,null,2))+'</pre></div>'}
 $("#page").innerHTML=h; bind();
}
function bind(){
 document.querySelectorAll("details[data-group]").forEach(d=>d.addEventListener("toggle",()=>{s.openGroups[d.dataset.group]=d.open;save()}));
 document.querySelectorAll("[data-basic]").forEach(e=>e.oninput=()=>{s.basic[e.dataset.basic]=e.value;save()});
 document.querySelectorAll("[data-family]").forEach(e=>e.oninput=()=>{s.family[e.dataset.family]=e.value;save()});const fin=$("#finance");if(fin){fin.value=s.family.finance;fin.onchange=()=>{s.family.finance=fin.value;if(s.school&&!eligibleSchool(s.school).ok){s.school="";s.house="";s.residence=""}save();render()}}
 document.querySelectorAll("[data-side]").forEach(e=>e.onclick=()=>{s.residentialAccess=e.dataset.side;save();render()});
 document.querySelectorAll("[data-gender]").forEach(e=>e.onclick=()=>{s.basic.gender=e.dataset.gender;s.residentialAccess=null;s.buildingId=null;if(s.school&&!eligibleSchool(s.school).ok){s.school="";s.house="";s.residence=""}save();render()});
 document.querySelectorAll("[data-school]").forEach(e=>e.onclick=()=>{if(!eligibleSchool(e.dataset.school).ok)return;s.school=e.dataset.school;s.house="";s.residence="";save();render()});
 document.querySelectorAll("[data-house]").forEach(e=>e.onclick=()=>{s.house=e.dataset.house;save();render()});
 document.querySelectorAll("[data-res]").forEach(e=>e.onclick=()=>{s.residence=e.dataset.res;save();render()});
 const ex=$("#experience");if(ex)ex.oninput=()=>{s.experience=ex.value;save()};const ra=$("#rollAttr");if(ra)ra.onclick=()=>randomize("attr",Object.keys(s.attr));const rac=$("#rollAcademic");if(rac)rac.onclick=()=>randomize("academic",academics);const rs=$("#rollSkills");if(rs)rs.onclick=()=>randomize("skills",Object.values(groups).flat());document.querySelectorAll("[data-score]").forEach(e=>e.onchange=()=>{const [kind,name]=e.dataset.score.split("|");s[kind][name]=Math.max(0,Math.min(75,Number(e.value)||0));save();render()});const d=$("#dev");if(d)d.onchange=()=>{s.dev=d.checked;save()};
 document.querySelectorAll("[data-plus],[data-minus]").forEach(e=>e.onclick=()=>{const raw=e.dataset.plus||e.dataset.minus,[kind,name]=raw.split("|"),obj=s[kind],delta=e.dataset.plus?5:-5;obj[name]=Math.max(0,Math.min(75,(obj[name]||0)+delta));save();render()});
}
$("#steps").onclick=e=>{const b=e.target.closest("[data-go]");if(b){s.page=+b.dataset.go;save();render()}};
$("#back").onclick=()=>{if(s.page){s.page--;save();render()}};
function finish(){
 if(!s.school||!eligibleSchool(s.school).ok){s.page=5;save();render();alert("請選擇符合資格的學校。");return;}
 if(s.school==="coed"){
  try{Object.assign(s,assignResidence(s));s.residence="campus";}catch(error){s.page=6;save();render();alert(error.message);return;}
 }
 save();localStorage.setItem("clearwater-life-player-state-v1",JSON.stringify({saveVersion:1,createdAt:new Date().toISOString(),player:s}));
 if(s.school==="coed")location.href="../ravenwood/";else alert("Player State 已保存。此學校的地圖尚未接入；Ravenwood 已開放校園測試。");
}
$("#next").onclick=()=>{if(s.page<7){if(s.page===6&&s.school==="coed"&&!residentialSide(s.basic.gender,s.residentialAccess)){alert("請選擇住宿側。");return;}s.page++;save();render()}else finish()};
render();
