import test from 'node:test';import assert from 'node:assert/strict';
import {newCharacter,finishCharacter,validateCharacter} from '../web/creation-v2/creator-service.mjs';
import {allocate} from '../web/creation-v2/allocation-engine.mjs';
import {categoryStatus,proficiencyRemaining} from '../web/creation-v2/point-source-ledger.mjs';
import {schoolEligibility} from '../web/creation-v2/school-eligibility.mjs';
import {newRun,readRun,rollFinance} from '../web/creation-v2/finance.mjs';
const store=()=>{const map=new Map;return {getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)}};
function ready(){const s=newCharacter();for(const id of ['STR','CON','AGI','DEX','PER','INT'])allocate(s,'attribute',id,id==='STR'||id==='CON'?60:id==='AGI'||id==='DEX'?60:55);s.basic={name:'測試',month:'9',day:'1',gender:'female',pronouns:'她'};s.motherTongue='中文';s.school='girls';return s}
test('350 total, 65 cap, shared category formula',()=>{const s=ready();assert.equal(Object.values(s.attributes).reduce((a,b)=>a+b),350);assert.throws(()=>allocate(s,'attribute','STR',66));allocate(s,'attribute','STR',45);allocate(s,'attribute','INT',45);allocate(s,'attribute','DEX',65);allocate(s,'attribute','PER',65);assert.equal(categoryStatus(s,'藝術').total,172);allocate(s,'skill','繪畫',65);allocate(s,'skill','設計',65);assert.equal(categoryStatus(s,'藝術').allocated,130);assert.throws(()=>allocate(s,'skill','設計',66));});
test('mother tongue grant and separated proficiency pool',()=>{const s=ready();assert.equal(categoryStatus(s,'語言').allocated,0);allocate(s,'skill','母語',60);assert.equal(categoryStatus(s,'語言').allocated,5);assert.equal(proficiencyRemaining(s),500);allocate(s,'proficiency','鋼琴',75);assert.equal(proficiencyRemaining(s),425);assert.throws(()=>allocate(s,'proficiency','鋼琴',76));assert.equal(categoryStatus(s,'音樂').allocated,0)});
test('attribute decrease preserves overspent skills and blocks final',()=>{const s=ready();allocate(s,'skill','繪畫',65);allocate(s,'skill','設計',65);allocate(s,'skill','攝影',10);allocate(s,'attribute','DEX',0);assert.equal(s.skills['繪畫'],65);assert(categoryStatus(s,'藝術').remaining<0);assert(validateCharacter(s,{locked:true}).some(x=>x.includes('藝術')))});
test('run roll immediately persists and only new run rerolls',()=>{const storage=store();const first=newRun(storage,'a');const locked=rollFinance(storage,()=>({tierId:'test-a'}));assert.equal(readRun(storage).result.tierId,'test-a');assert.deepEqual(rollFinance(storage,()=>{throw Error('rerolled')}),locked);newRun(storage,'b');assert.equal(readRun(storage).locked,false);assert.equal(rollFinance(storage,()=>({tierId:'test-b'})).result.tierId,'test-b');assert.equal(first.id,'a')});
test('school gating and player state without residence assignment',()=>{const s=ready(),roll={id:'run',locked:true,result:{tierId:'test'}};assert.equal(schoolEligibility(s,'girls',null).ok,false);const state=finishCharacter(s,roll);assert.equal(state.phase,'preparation_week');assert.equal(state.player.residence.status,'pending_preparation_week');assert.equal(state.player.residence.assignment,null);assert.equal(state.player.schoolRegistration.schoolId,'girls');assert.equal(JSON.parse(JSON.stringify(state)).player.familyFinance.tierId,'test')});
test('opening UI only references portrait on page 01 and preserves scroll/group state',async()=>{const fs=await import('node:fs/promises');const app=await fs.readFile('web/opening/app.mjs','utf8');assert.match(app,/s\.openGroups\[id\]/);assert.match(app,/s\.scroll\[s\.page===3/);assert.match(app,/case 7:\{/);assert.doesNotMatch(app.slice(app.indexOf('case 7:{'),app.indexOf('page.innerHTML=html')),/portraitSource|portraitUpload/)});
